// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wexbgphkfsswbaniibye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleGJncGhrZnNzd2JhbmlpYnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTIwODcsImV4cCI6MjA2ODc4ODA4N30.6oj0ofPKy3UdrTp8ZJzBQWKc5yYFxHjQu43P8aU-s08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});